@startuml

start

:Step 1;

if (condition is true?) then (yes)
    :condition is true;
else (no)
    :condition is false;
endif

:Step 2;

fork
    :Step 3 (parallel);
fork again
    :Step 4 (parallel);
end fork

:Step 5;

switch (case?)
case (case 1)
    : Case 1;
case (case 2)
    : Case 2;
endswitch

while (condition?) is (yes)
    :Step 6;
backward :Check again;
endwhile (no)

repeat :Step 7;
    :Step 8;
backward :Repeat;
repeat while (done ?) is (no)
->yes;

stop

@enduml
