@startuml

interface InterfaceClass {
    + {abstract} virtualMethod()
}

note right of InterfaceClass::virtualMethod
    virtual void virtualMethod() = 0;
end note

class ConcreteClass {
    + virtualMethod()
}

InterfaceClass <|.. ConcreteClass

@enduml
